spring:
  datasource:
    url:
    #  jdbc:h2:mem:testdb
      jdbc:h2:~/diceGame
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true